In [1]:
import sklearn

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.utils import shuffle

In [4]:
a=pd.read_csv('crop_predict.csv')
a = shuffle(a)
a

Moisture  Nitrogen  Phosphorous  Potassium              Crop_Name
2095   13.010234  0.918769     0.095013   1.517820  Corn-Field for stover
3372   12.989684  0.960511     0.088278   1.540944  Corn-Field for stover
8174   48.000686  1.822944     0.227955   2.299629                 Potato
7812   10.867177  2.751152     0.263354   1.046432                 Millet
3447   13.031478  1.035729     0.057329   1.578485  Corn-Field for stover
7257   10.610068  2.394452     0.416148   1.531972                 Millet
9740   48.000219  1.900500     0.228585   2.300934                 Potato
1744   72.826470  1.189738     0.319186   0.931840  Corn-Field for silage
100    72.447145  1.486213     0.326509   0.828202  Corn-Field for silage
5983   12.224047  1.961130     0.338702   1.592213                 Barley
4820   12.179045  2.053505     0.366837   1.603660                 Barley
11840  34.999517  0.091808     0.014133   1.902113              Sugarcane
9679   47.997030  1.871030     0.230185   2.297690                 Potato
5139   11.323289  1.924276     0.413484   1.613788                 Barley
63     73.315238  1.452161     0.238918   1.270673  Corn-Field for silage
5850   13.371393  1.874135     0.413722   1.597967                 Barley
7828    9.805259  1.946518     0.177406   1.526037                 Millet
2118   12.709540  1.011807     0.118376   1.581441  Corn-Field for stover
9542   47.998869  1.937866     0.228993   2.301166                 Potato
157    73.201492  1.346002     0.126986   1.246806  Corn-Field for silage
6176   10.190735  2.205855     0.421311   1.685030                 Millet
2509   12.902077  0.980245     0.120006   1.558647  Corn-Field for stover
489    73.210144  1.243082     0.218207   1.501600  Corn-Field for silage
4671   13.721651  1.867694     0.408081   1.580951                 Barley
8939   47.999661  1.890184     0.229337   2.301383                 Potato
391    73.816631  1.353265     0.191138   1.089925  Corn-Field for silage
11181  35.000591  0.088938     0.015311   1.894059              Sugarcane
5880   13.234907  1.936416     0.342994   1.605116                 Barley
11518  34.999386  0.088262     0.017356   1.898378              Sugarcane
4772   12.677626  1.860650     0.398419   1.590379                 Barley
...          ...       ...          ...        ...                    ...
9229   47.999379  1.882880     0.229939   2.300908                 Potato
3768   12.937414  0.941493     0.100277   1.549276  Corn-Field for stover
2179   12.981841  0.972401     0.087060   1.520570  Corn-Field for stover
10246  34.997674  0.090697     0.020416   1.896870              Sugarcane
9171   47.999542  1.960003     0.231441   2.300201                 Potato
1457   73.027708  1.239718     0.264537   1.127072  Corn-Field for silage
5110   12.584387  2.108103     0.353330   1.578451                 Barley
9743   47.998876  1.879002     0.227762   2.301089                 Potato
2382   13.004321  1.019604     0.094865   1.581107  Corn-Field for stover
3264   12.910638  0.981159     0.091516   1.529307  Corn-Field for stover
8358   48.001151  1.870857     0.231019   2.299205                 Potato
1018   72.778137  1.246875     0.227498   1.140534  Corn-Field for silage
7011    9.957517  1.612649     0.277610   1.606879                 Millet
6828   10.078121  2.424976     0.570926   1.215935                 Millet
11751  34.999336  0.090692     0.013719   1.905811              Sugarcane
3168   12.907920  0.909534     0.105282   1.530074  Corn-Field for stover
7636   10.214914  1.577345     0.212469   2.130949                 Millet
940    73.404299  1.181590     0.329674   1.438177  Corn-Field for silage
10667  35.002092  0.091630     0.016522   1.895212              Sugarcane
3548   12.701951  1.058764     0.075056   1.558640  Corn-Field for stover
8511   48.002472  1.953078     0.229567   2.300242                 Potato
1226   72.078513  1.072171     0.344575   1.267362  Corn-Field for silage
1360   73.06

In [5]:
X = a.drop(['Crop_Name'],axis = 1)
X

Moisture  Nitrogen  Phosphorous  Potassium
2095   13.010234  0.918769     0.095013   1.517820
3372   12.989684  0.960511     0.088278   1.540944
8174   48.000686  1.822944     0.227955   2.299629
7812   10.867177  2.751152     0.263354   1.046432
3447   13.031478  1.035729     0.057329   1.578485
7257   10.610068  2.394452     0.416148   1.531972
9740   48.000219  1.900500     0.228585   2.300934
1744   72.826470  1.189738     0.319186   0.931840
100    72.447145  1.486213     0.326509   0.828202
5983   12.224047  1.961130     0.338702   1.592213
4820   12.179045  2.053505     0.366837   1.603660
11840  34.999517  0.091808     0.014133   1.902113
9679   47.997030  1.871030     0.230185   2.297690
5139   11.323289  1.924276     0.413484   1.613788
63     73.315238  1.452161     0.238918   1.270673
5850   13.371393  1.874135     0.413722   1.597967
7828    9.805259  1.946518     0.177406   1.526037
2118   12.709540  1.011807     0.118376   1.581441
9542   47.998869  1.937866     0.228993   2.301166
157    73.201492  1.346002     0.126986   1.246806
6176   10.190735  2.205855     0.421311   1.685030
2509   12.902077  0.980245     0.120006   1.558647
489    73.210144  1.243082     0.218207   1.501600
4671   13.721651  1.867694     0.408081   1.580951
8939   47.999661  1.890184     0.229337   2.301383
391    73.816631  1.353265     0.191138   1.089925
11181  35.000591  0.088938     0.015311   1.894059
5880   13.234907  1.936416     0.342994   1.605116
11518  34.999386  0.088262     0.017356   1.898378
4772   12.677626  1.860650     0.398419   1.590379
...          ...       ...          ...        ...
9229   47.999379  1.882880     0.229939   2.300908
3768   12.937414  0.941493     0.100277   1.549276
2179   12.981841  0.972401     0.087060   1.520570
10246  34.997674  0.090697     0.020416   1.896870
9171   47.999542  1.960003     0.231441   2.300201
1457   73.027708  1.239718     0.264537   1.127072
5110   12.584387  2.108103     0.353330   1.578451
9743   47.998876  1.879002     0.227762   2.301089
2382   13.004321  1.019604     0.094865   1.581107
3264   12.910638  0.981159     0.091516   1.529307
8358   48.001151  1.870857     0.231019   2.299205
1018   72.778137  1.246875     0.227498   1.140534
7011    9.957517  1.612649     0.277610   1.606879
6828   10.078121  2.424976     0.570926   1.215935
11751  34.999336  0.090692     0.013719   1.905811
3168   12.907920  0.909534     0.105282   1.530074
7636   10.214914  1.577345     0.212469   2.130949
940    73.404299  1.181590     0.329674   1.438177
10667  35.002092  0.091630     0.016522   1.895212
3548   12.701951  1.058764     0.075056   1.558640
8511   48.002472  1.953078     0.229567   2.300242
1226   72.078513  1.072171     0.344575   1.267362
1360   73.062725  1.332042     0.337508   1.003940
5730   13.457269  1.908721     0.380708   1.613822
9083   47.997256  1.884691     0.229684   2.299116
5326   12.091935  1.845781     0.465347   1.598222
11625  34.998937  0.090251     0.017424   1.903803
7719   10.091086  2.290548     0.394664   1.333382
9084   48.000369  1.894944     0.227992   2.299447
9425   47.997870  1.906119     0.230258   2.300788

[12000 rows x 4 columns]

In [6]:
Y = a['Crop_Name']
unique_names = np.unique(a['Crop_Name'])
unique_names
Y=Y.to_frame()
Y

Crop_Name
2095   Corn-Field for stover
3372   Corn-Field for stover
8174                  Potato
7812                  Millet
3447   Corn-Field for stover
7257                  Millet
9740                  Potato
1744   Corn-Field for silage
100    Corn-Field for silage
5983                  Barley
4820                  Barley
11840              Sugarcane
9679                  Potato
5139                  Barley
63     Corn-Field for silage
5850                  Barley
7828                  Millet
2118   Corn-Field for stover
9542                  Potato
157    Corn-Field for silage
6176                  Millet
2509   Corn-Field for stover
489    Corn-Field for silage
4671                  Barley
8939                  Potato
391    Corn-Field for silage
11181              Sugarcane
5880                  Barley
11518              Sugarcane
4772                  Barley
...                      ...
9229                  Potato
3768   Corn-Field for stover
2179   Corn-Field for stover
10246              Sugarcane
9171                  Potato
1457   Corn-Field for silage
5110                  Barley
9743                  Potato
2382   Corn-Field for stover
3264   Corn-Field for stover
8358                  Potato
1018   Corn-Field for silage
7011                  Millet
6828                  Millet
11751              Sugarcane
3168   Corn-Field for stover
7636                  Millet
940    Corn-Field for silage
10667              Sugarcane
3548   Corn-Field for stover
8511                  Potato
1226   Corn-Field for silage
1360   Corn-Field for silage
5730                  Barley
9083                  Potato
5326                  Barley
11625              Sugarcane
7719                  Millet
9084                  Potato
9425                  Potato

[12000 rows x 1 columns]

In [7]:
mapping = { 'Barley' : 0 , 'Corn-Field for silage':1, 'Corn-Field for stover':2,'Millet':3,'Potato':4,'Sugarcane':5 }

In [8]:
Y.Crop_Name = Y.Crop_Name.map(mapping)
Y

Crop_Name
2095           2
3372           2
8174           4
7812           3
3447           2
7257           3
9740           4
1744           1
100            1
5983           0
4820           0
11840          5
9679           4
5139           0
63             1
5850           0
7828           3
2118           2
9542           4
157            1
6176           3
2509           2
489            1
4671           0
8939           4
391            1
11181          5
5880           0
11518          5
4772           0
...          ...
9229           4
3768           2
2179           2
10246          5
9171           4
1457           1
5110           0
9743           4
2382           2
3264           2
8358           4
1018           1
7011           3
6828           3
11751          5
3168           2
7636           3
940            1
10667          5
3548           2
8511           4
1226           1
1360           1
5730           0
9083           4
5326           0
11625          5
7719           3
9084           4
9425           4

[12000 rows x 1 columns]

In [9]:
Y = Y.values.tolist()
Y = np.asarray(Y)

In [10]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder(sparse=False)
Y = Y.reshape(len(Y), 1)
y = onehot_encoder.fit_transform(Y)
print(y)



[[ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 ..., 
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.  0.]]


In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
print y_train.shape
print y_test.shape

(8400, 6)
(3600, 6)


In [15]:
rf = RandomForestClassifier(n_estimators=145)
rf.fit(X_train, y_train)
print rf.score(X_test, y_test)

0.996666666667


In [16]:
import pickle

In [17]:
filename = 'Crop_pred_rand_forest.pkl'

In [18]:
pickle.dump(rf,open(filename, 'wb'))

In [42]:
test_vector = np.asanyarray([12, 2, 0.3, 1.5])
test_vector = np.reshape(test_vector,(1,4))
reverse_mapping = ['Barley','Corn-Field for silage','Corn-Field for stover','Millet','Potato','Sugarcane']
reverse_mapping = np.asarray(reverse_mapping)
a = rf.predict(test_vector)
#hell yeah this corresponds to barley
# prediction = reverse_mapping[a]

c=0
for ix in range(a.shape[0]):
    if a[ix].any() == 1:
        ans = c
    c+=1

print reverse_mapping[ans]

Barley
